version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - /home/pan/tttm/redis/redis.conf:/etc/redis/redis.conf
      - /home/pan/tttm/redis/data:/data
      - /home/pan/tttm/redis/redis.log:/redis/redis.log
    command: redis-server /etc/redis/redis.conf